// <auto-generated />
using System;
using FilRougeApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FilRougeApi.Migrations
{
    [DbContext(typeof(FilRougeContext))]
    partial class FilRougeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FilRougeApi.Models.Formation", b =>
                {
                    b.Property<long>("FormationID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date_Deb");

                    b.Property<int>("Duree");

                    b.Property<long>("PersonneID");

                    b.Property<string>("Titre");

                    b.HasKey("FormationID");

                    b.HasIndex("PersonneID");

                    b.ToTable("Formation");
                });

            modelBuilder.Entity("FilRougeApi.Models.Personne", b =>
                {
                    b.Property<long>("PersonneID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nom");

                    b.Property<string>("Prenom");

                    b.HasKey("PersonneID");

                    b.ToTable("Personne");
                });

            modelBuilder.Entity("FilRougeApi.Models.Formation", b =>
                {
                    b.HasOne("FilRougeApi.Models.Personne", "Personne")
                        .WithMany("Formations")
                        .HasForeignKey("PersonneID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
